### ISSUE TITLE
Doesn't run on iOS (RN 0.60+): React/RCTAnimationType.h file not found

### ISSUE THREAD

**Issue by JustinRohweller** [FidelLimited/rn-sdk#11]
###### Package.json: 
``` 
{
  "name": "FidelTest",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "fidel-react-native": "^1.0.5",
    "react": "16.8.6",
    "react-native": "0.60.5"
  },
  "devDependencies": {
    "@babel/core": "^7.5.5",
    "@babel/runtime": "^7.5.5",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.9.0",
    "eslint": "^6.2.1",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.56.0",
    "react-test-renderer": "16.8.6"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

**Comment by JustinRohweller** [comment]
##### Wanted to update this, just tested their example project as well with the same result, Install example project, yarn, follow installation instructions, clean, build, I get errors:
###### Use of undeclared identifier 'FLCountryCanada' did you mean 'FLCountryJapan'? in RCTConvert+Country.h. Fixed by deleting all options other than @"noDefault":
###### Property 'objc_supportedCardSchemes' not found on object of type FLFidel' in FLRNOptionsAdapter.m

**Comment by JustinRohweller** [comment]
Found problem with the FLCountryCanada. In Fidel-Swift.h, FLCountryCanada is not in the Swift enum. at line 395.

**Comment by JustinRohweller** [comment]
Unfortunately changing that then results in various other errors popping up. Doesn't seem like something I can fix myself.

**Comment by c0derabbit** [comment]
@JustinRohweller we've found the issue, our SDK is currently not playing well with react-native 0.60. Please bootstrap your app using `react-native init --version="react-native@0.59.0" yourProject`.
We'll keep this issue open and work on adjusting to RN 0.60+

**Comment by JustinRohweller** [comment]
Turns out it actually was a few separate issues. Basically, I am using the Expo bare workflow to quickstart my project, and this causes the podfile to default to platform: 10.0, which Fidel doesn't like, but instead wants 9.1. If you set the podfile to 9.1, you cannot use Expo's bare workflow, which has several packages that require platform 10.0

**Comment by JustinRohweller** [comment]
The other issue is like you said, doesn't work with 0.60

**Comment by SMJ93** [comment]
Hey,

Any update on this? It's blocking us from upgrading to 0.60.

**Comment by ccorneliu** [comment]
Hi!

Sorry for the delay, but we got it fixed. Please update to the latest released version: 1.2.0. Also, please check the automatic linking instructions. They should work if you use RN >= 0.6.0.

Please let me know, if you encounter any other issues.

Thank you for your patience.

**Comment by SMJ93** [comment]
Hi @ccorneliu, I am still getting the following error after updating:

```
In file included from /Users/a/Documents/work/b/c/node_modules/fidel-react-native/ios/RCTConvert+Options.m:9:
In file included from /Users/a/Documents/work/b/c/node_modules/fidel-react-native/ios/RCTConvert+Options.h:13:
../../react-native/React/Base/RCTConvert.h:11:9: fatal error
: 'React/RCTAnimationType.h' file not found
#import <React/RCTAnimationType.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

Guessing you need to add the import checks to some of the other files similar to what you've done in this commit: https://github.com/FidelLimited/rn-sdk/commit/395ef6e57a57b4ef5f4fad6e2c082c079808d6a7

**Comment by SMJ93** [comment]
Got it working now, thanks @ccorneliu! We had to manually remove `fidel-react-native` from `ios/app.xcodeproj/project.pbxproj`.

Might be worth adding this to a troubleshooting / update guide?
